title: ♡ janymuong # name of the site
author: Jany Muong # name of site's author
email: me.roumuong@gmail.com # email of site's author
url: https://janymuong.github.io # root address of the site
baseurl: "/" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed) 
  <p> 
  <h2 align="center"><code>Hello, World</code> <a href="https://github.com/janymuong" target="_blank"><img align="center" src="/img/VgCDAzcKvsR6OM0uWg.webp" title="GitHub" alt="@janymuong" height="40" width="64" style="padding-right:10px;" /></a>:</h2>
  
  I am <a href="https://www.github.com/janymuong/" target="_blank">Jany Muong</a>. Think of me as a Machine Learning and Cloud DevOps/Software Engineer, with a <strong>Computer Science</strong> background. <br><br>
  
  <strong>About ME:</strong><br>
  I use mainly <code>Python</code> and <code>TensorFlow</code>, and <code>Amazon Web Services (AWS)</code>, and I like packaging <code>ML</code> models in backend applications. <br><br>
  
  <blockquote>⚡<strong>Fun Fact:</strong> I am (overly) obsessed with <strong>command-line interfaces (CLIs)</strong>.</blockquote><br>
  
  <strong>STUFF:</strong><br>
  This covers (a subset of) languages, frameworks and tools, that I work with.<br>
  <p align="left">
    <a href="https://www.python.org" target="_blank">
      <img src="/img/python.svg" alt="Python" title="Python" width="48" height="40"/>
    </a> 
    <a href="https://www.tensorflow.org/" target="_blank">
      <img src="/img/TF.svg" alt="TensorFlow" width="170" />
    </a>
    <a href="https://www.postgresql.org/" target="_blank"> 
      <img src="https://www.vectorlogo.zone/logos/postgresql/postgresql-icon.svg" title="PostgreSQL" alt="postgreSQL" width="36" height="36"/>
    </a>
    <a href="https://www.docker.com" target="_blank">
      <img src="/img/docker.png" alt="docker" width="42" height="36"/>
    </a>
    <a href="https://kubernetes.io/" target="_blank">
      <img src="/img/kubernetes.svg" title="Kubernetes" alt="Kubernetes" width="36" height="36"/>
    </a>
    <a href="https://aws.amazon.com" target="_blank">
      <img src="/img/aws.svg" title="Amazon Web Services" alt="aws" width="48px" height="40px"/>
    </a>
  </p><br>
  
  <strong>Tool Setup ⚙️:</strong><br>
  This segment lists out editors and command-line utilities that I use.<br>
  <p align="left">
    <img src="/img/terminal-dark.svg" alt="shell" title="Terminal/Shell" height="35" width="30px"/>
    <img src="/img/neovim.svg" height="40px" width="64px" title="UNIX neovim" />
    <a href="https://code.visualstudio.com/" target="_blank">
      <img alt="Visual Studio Code" width="30px" height="24" src="/img/vs_code.svg" style="padding-right:10px;" title="VS Code"/>
    </a>
    <a href="https://aws.amazon.com/cloud9/" target="_blank">
      <img src="/img/cloud9.svg" alt="al2" title="Amazon Linux 2 Cloud9 IDE" height="24" width="32px" />
    </a>
  </p><br>
  
  <div>
    <img title="archlinux" alt="Arch Linux" width="32px" src="/img/arch.png" style="padding-right:0px;" />
    <code>I use arch btw :)</code> 
  </div><br>
  
  <hr>
  <strong>CONNECT with ME on the INTERNET:</strong><br>
  <p align="left">
    <a href="https://twitter.com/janymuong/" target="_blank"><img align="center" src="/img/twitter-x.svg" title="Twitter/X" alt="janymuong" height="24" width="40" style="padding-right:10px;" /></a>
    <a href="https://www.reddit.com/user/stackjvnkie/" target="_blank"><img align="center" src="/img/reddit.svg" title="Reddit" alt="@janymuong" height="60" width="74" style="padding-right:10px;" /></a>
    <a href="https://www.linkedin.com/in/janymuong/" target="_blank"><img align="center" src="/img/linkedin-light.svg" title="LinkedIn" alt="@janymuong" height="24" width="40" style="padding-right:10px;" /></a> 
    <a href="https://www.twitch.tv/janymuong/" target="_blank"><img align="center" src="/img/twitch.svg" title="Twitch" alt="@janymuong" height="24" width="40" style="padding-right:10px;" /></a> 
    <a href="https://leetcode.com/u/janymuong/" target="_blank"><img align="center" src="/img/leetcode.png" title="LeetCode" alt="@janymuong" height="24" width="40" style="padding-right:10px;" /></a>
    <a href="https://discord.com/janymuong#0/" target="_blank"><img align="center" src="/img/discord-dark.svg" title="Discord" alt="@janymuong" height="22" width="40" style="padding-right:10px;" /></a>
  </p>
  Always interested in working on cool projects - feel free to reach out! <br>
  </p>

permalink: /:slug.html

favicon: "icons8-disco-ball-96.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  reco:
    output: true
