title: ♡ janymuong # name of the site
author: Jany Muong # name of site's author
email: me.roumuong@gmail.com # email of site's author
url: https://janymuong.github.io # root address of the site
baseurl: "/" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed) 
  <p> <span style="color: #FFFFFF; font-size: 1.2em;">上帝保佑你</span> <br> Here's my only fixed address <br> i travel, run a small clothing business and study CS (MSc) <br> always interested in working on cool projects : feel free to reach out! <br>  <br> > doing a retreat somewhere in europe <br>  <br> <span style="color: #FFFFFF;"> <span style="font-size: 40px;">️ ☣ </span> </span>  <a href="https://open.spotify.com/user/auwtkox85ovn7ahyyvuv64gql?si=cded6bf4e4ac4a8f" style="color: #FFFFFF;">
    <span style="color: #FFFFFF;">  listen to my sick playlists </span> </a> <span style="color: #FFFFFF;"> <span style="font-size: 40px;">️ ☣ </span> </span> <br> <br> interest : bio/ml, computer arch, theology, philosophy, music, arts, poetry, opera, theater, horror, books, hiking, experiencing, learning... <br> <br> sweet hate : journalism, ideology, <a href="/assets/badfaith.pdf" target="_blank" style="color: #FFFFFF;">this</a>, advertising, 2-factor authentication and Windows   <br> </p>

permalink: /:slug.html

favicon: "icons8-disco-ball-96.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  reco:
    output: true
